### ISSUE TITLE
Apply Masking on CNIC

### ISSUE THREAD

**Issue by AnasShafqat** [ranafaraz/dba_db#1]
# Masking

- Masking must be applied on CNIC.
- As CNIC is of 13 characters & it contains 2 dashes as well, the masked field shall look like this: 00000-0000000-0.

**Comment by ranafaraz** [comment]
You better use masking widgets to achieve this task. Here is the link: https://github.com/yiisoft/yii2-maskedinput

**Comment by ranafaraz** [comment]
# Task Accomplished
- The masking has been applied using the solution given above.
- The issue is liable to be closed.
