### ISSUE TITLE
Apply Gentellela theme

### ISSUE THREAD

**Issue by ranafaraz** [ranafaraz/dba_db#6]
# Details
### Apply this theme to the subject web application.

**Comment by AnasShafqat** [comment]
Gentellela Bootstrap Dashboard has been integrated with login page.

**Comment by ranafaraz** [comment]
## Class 'yiister\gentelella\assets\Asset' not found

**Comment by ranafaraz** [comment]
## Issue Resolved
### The error came because the remote repo was updated but gitignore file discourages to upload the vendor directory and the theme files were in that. Because the vendor directory was not available in the remote repo thats why the other collaborators were not able to get the expected output.
### To run application with gentelella, individual collaborator has to install gentelella in their local repositories or the developer responsible for template integration shall upload his local vendor directory to the remote repository.
